### ISSUE TITLE
Make the invisible files go away

### ISSUE THREAD

**Issue by bre** [makerbot/ReplicatorG#102]
For n00bs, the invisible files are very confusing and make using new skeinforge profiles nearly impossible. If they could become visible files, life would be better for the non-command line user. - Bre

**Comment by phooky** [comment]
What are you talking about?

**Comment by tmophoto** [comment]
there is currently no way to access (to delete) skeinforge profiles unless you make invisible files visible then go into the .skeinforge folder or you know how to directly access it with the command line in osx.  something beginners/99% of mac users probably dont know anything about.
