### ISSUE TITLE
Support material settings in skeinforge

### ISSUE THREAD

**Issue by bre** [makerbot/ReplicatorG#104]
Right now there is just a support material button but no configuration settings. It would be great to be able to change density of that

**Comment by bre** [comment]
Ok, so after trying it. Here's my parameter wishlist. 
1. speed of support material filament. If we can make it go faster, it'll be thinner and more easy to break away.
2. Distance from model. How far do you want your support material away from the model. Because the extrusion splooges out a bit, it would be good to be able to adjust this.
3. Angle of support. Really we only need support material in places where the model is at an angle of less than 45. Would be nice to be able to change that so that if you're MakerBot is tuned you could get it so that it would only add support in areas less than 30 degree angle overhangs.

**Comment by ssd2** [comment]
First, these things are in skeinforge, not ReplicatorG.

Second, some of these already exist.  #3 I am sure exists.

**Comment by DaveDurant** [comment]
Yes. The current/latest skeinforge has angle, distance and flow rate settings. There are also settings for how to draw the support stuff (just on X or X and Y on alternating layers) and what works out to a setting to support just internal structures, just external ones or both.

A feed rate modifier would also be quite nice but I think the existing flow rate modifier gets you most of the way there.
