### ISSUE TITLE
feature request:  forward and back buttons for MBI ABP

### ISSUE THREAD

**Issue by tmophoto** [makerbot/ReplicatorG#105]
forward and back buttons for Makerbot Industries new Automated Build Platform in the control panel window

could look something like this
http://farm5.static.flickr.com/4088/5001587257_58b583a4fd_z.jpg

**Comment by phooky** [comment]
We can relabel the fan controls, but in the current configuration the ABP motor is currently driven by a mosfet; there's no way in software to make it run in reverse.

**Comment by tmophoto** [comment]
ok thanks, i mainly wanted so i could test the belt before getting it all installed in the machine.  in general day to day use i guess its not that critical unless something goes wrong with a build and you need to abort.  then a forward advance button would be handy.

**Comment by phooky** [comment]
This would require hardware changes; closing this from the software side
