### ISSUE TITLE
feature request: method for opening multiple files for ABP

### ISSUE THREAD

**Issue by tmophoto** [makerbot/ReplicatorG#107]
currently the ABP is basically only capable of printing multiples of one thing in replicatorG without leaving the app. 

if we could somehow open a new file while retaining the gcode of the current file it would be great.   basically :  open #1 object, create gcode, close and save and still have gcode tab.  open #2, create gcode, paste #2 into #1 gcode, close #2, save it, open #3, greate gcode paste into #1, close #3, save and so on.

as a way to do it now you can paste gcode into a texedit app one after another when you are done adding objects paste it all back into repG.

**Comment by phooky** [comment]
Build queueing is on its way; you won't need to do any cutting and pasting in the next version.

**Comment by tmophoto** [comment]
sounds great thanks.

**Comment by ssd2** [comment]
Build queueing.... hmmmm...

Can we queue builds of parts already on the sd card?
Like, I want 5 of part A and 6 of part B ... or maybe just one of everything...

And while I'm going all wild and crazy and suggesting features, can we shuffle them and print them in a random order?  :)

**Comment by D1plo1d** [comment]
see https://github.com/d1plo1d/ReplicatorG for the super top secret build queue ReplicatorG dev fork :)

No sd card support yet or in my short term dev effort (not a high priority itch to scratch for me, sorry). Shuffle would be very cool. I want to have loops and the ability to write (serialize) build queues to files.

Features so far:
- add multiple files at a time to the queue
- automatically convert every stl in the queue to gcode and then print it (this only works if you don't add stls after the print starts)
- iterations so you can set the number of each part to print

PS. anyone who wants to help me dev this is more then welcome!

PPS. sorry this features taking so long to roll-out, volunteer effort here :)

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
