### ISSUE TITLE
Don't zero z-axis in end.gcode

### ISSUE THREAD

**Issue by seibert** [makerbot/ReplicatorG#113]
In ReplicatorG 0019, it appears that the ending gcode file rezeros the z-axis at the top of the print.  As a result, at the end of every print the head thinks it is at (0,0,10).  This annoyingly requires the user to rezero the head on the build platform by hand before the next print.

**Comment by DaveDurant** [comment]
I think this is actually in the start.gcode file but yeah, I agree. Removing that line makes it a lot easier if you're printing multiple objects.

**Comment by seibert** [comment]
Actually, that's a different thing.  It appears that the offending lines in end.txt are:

G92 Z0 (zero our z axis - hack b/c skeinforge mangles gcodes in end.txt)
G1 Z10 (go up 10 b/c it was zeroed earlier.)
G1 X0 Y0 Z10 (go to 0,0,z)

Clearly there is some other bug being worked around here, but the current hack is not ideal.

**Comment by DaveDurant** [comment]
Oh.. I was looking at repg 18, which only has that in the HBP profile.

Still, both profiles have a "G92 X0 Y0 Z0" in start.txt, which resets the position (in memory, no physical movement) back to 0/0/0. That also means you have to manually mess with the position at the start of every print, which is what I think the point of this issue is.

**Comment by ssd2** [comment]
There is a long standing bug in ReplicatorG that makes the firmware on the makerbot go insane if you don't start a print with a G92.  The bug works differently depending if you are printing via serial or printing via SD card.  This has irritated me for a long time, for exactly the reasons you have stated.

**Comment by DaveDurant** [comment]
They might have fixed that one, or at least lessened it. I commented out that G92 from my start.txt a month+ ago and it's been fine.. (of course now it will start freaking out, just because I said that..)

**Comment by koenkooi** [comment]
I've been using these start & end files for a few months now without problems: http://github.com/koenkooi/ReplicatorG/tree/koen/skeinforge/prefs/cupcake-hbp-makergear-035-abs-3.0mm/gcode_scripts

I left the warnings in, even if I can't reproduce the errors it is talking about

**Comment by kintel** [comment]
This is no longer an issue in the latest ReplicatorG using skeinforge 35.
