### ISSUE TITLE
Machine name in title bar

### ISSUE THREAD

**Issue by charlespax** [makerbot/ReplicatorG#116]
It would be nice to have the machine name as the first item in the title bar. Currently the tiele bar reads, "ReplicatorG - 0019". When connected to a MakerBot it should read the machine's name.

Example:  I have multiple bots in the Botfarm each with its own instance of ReplicatorG. With the windows minimized each instance looks the same in the task bar because the title bar of the main window reads, "ReplicatorG - 0019". If the title bar read the name of each machine, "Cupcake 2014", I would be able to easily identify which instance of ReplicatorG controls a particular machine.

**Comment by phooky** [comment]
- Added machine name or not connected to title bar as per Charles' request.  Closed by 5f778136b75540a9028ac269fff12ba6aafc0f96.
