### ISSUE TITLE
SF31 strips parenthetical statements from start and end files.

### ISSUE THREAD

**Issue by charlespax** [makerbot/ReplicatorG#117]
Skeinforge 31 strips parenthetical statements form the start and end files.

Original:
"""(Cupcake ABS with heated build platform skeinforge profile)
(beginning of start.txt)
M104 S220 T0 (Extruder Temperature to 220 Celsius)
M109 S110 T0 (Heated Platform Temperature to 110 Celsius)
M107 (fan off)
G21 (Metric FTW)
G90 (Absolute Positioning)
G92 X0 Y0 Z0 (You are now at 0,0,0)
(You have failed me for the last time, MakerBot)
G0 Z15 (Move up for warmup)
M108 S255 (Extruder speed = max)
M6 T0 (Wait for tool to heat up)
G04 P5000 (Wait 5 seconds)
M101 (Extruder on, forward)
G04 P5000 (Wait 5 seconds)
M103 (Extruder off)
M01 (The heated build platform is heating up. Wait until after the lights have turned off for the first time, clear the test extrusion, and click yes.)
G0 Z0    (Go back to zero.)
(end of start.txt)
"""

After going through skeinforge:
"""
M104 S220 T0 (Extruder Temperature to 220 Celsius)
M109 S110 T0 (Heated Platform Temperature to 110 Celsius)
M107 (fan off)
G21 (Metric FTW)
G90 (Absolute Positioning)
G92 X0 Y0 Z0 (You are now at 0,0,0)
G0 Z15 (Move up for warmup)
M108 S255 (Extruder speed = max)
M6 T0 (Wait for tool to heat up)
G04 P5000 (Wait 5 seconds)
M101 (Extruder on, forward)
G04 P5000 (Wait 5 seconds)
M103 (Extruder off)
M01 (The heated build platform is heating up. Wait until after the lights have turned off for the first time, clear the test extrusion, and click yes.)
G0 Z0    (Go back to zero.)
"""

**Comment by phooky** [comment]
There's an option on the export script module that strips comments.  I've turned this off in all the profiles in git.
