### ISSUE TITLE
Switch H Bridge 

### ISSUE THREAD

**Issue by bre** [makerbot/ReplicatorG#119]
We sometimes hear of people blowing their H-Bridge chip for the DC motor. There are two of them on the board and rather than unsoldering the good chip and using it to replace the bad chip, it would be awesome if the firmware could be configured in ReplicatorG to switch it so that they could just plug the DC motor into the other terminal.

**Comment by MakerBlock** [comment]
This would be a sweet fix!

**Comment by phooky** [comment]
Implemented in v2.5 extruder firmware and ReplicatorG 0020.
