### ISSUE TITLE
Patch for a number of fixes

### ISSUE THREAD

**Issue by justjoheinz** [makerbot/ReplicatorG#120]
I have created a patch which addresses a couple of features and bugs.
- show About panel on Windows (worked only in Mac OS X)
- disable Control Panel menu entry when machine is not connected
- Allow selection of profiles (e.g. for editing) when no model file is loaded (new menu entry in Build)
- support for renaming and deleting profiles
- Eclipse project files (.classpath, .project)

**Comment by justjoheinz** [comment]
Uups, where can I attach the patch file for review?

**Comment by koenkooi** [comment]
github only allows you to 'attach' merge request, so you are forced to create a repo fork, upload your commits, etc, etc, etc

**Comment by justjoheinz** [comment]
Dang! That exceeds my current github knowledge... I mailed my patch to bugs@makerbot.com. Thanks for the reply koenkooi!

**Comment by justjoheinz** [comment]
I close the issue, as I have now learned how to do it the proper way. Will create issues with the commits attached.
