### ISSUE TITLE
CRC error on reply causes build restart

### ISSUE THREAD

**Issue by D1plo1d** [makerbot/ReplicatorG#126]
We've been getting CRC errors on reply occasionally from our makerbot. I looked into the code and it appears these throw runtime exceptions which evidently propagate far enough to restart a print. IMHO CRC Errors should either cause the print to fail and exit or resend the erroneous packet but never restart (which causes the printer to move through existing printed material = very bad!)

**Comment by phooky** [comment]
That is very bad; I'll look at this right now.

**Comment by D1plo1d** [comment]
Thanks Phooky!

**Comment by phooky** [comment]
- Added retry and timeout fail on bad CRCs; doesn't seem like this has been a common problem for us in the past.  Currently defaults to retry three times when a bad CRC is recv'd (although I'm guessing bad crcs are related to sync issues and so the packet will fail on retries too).  Still need to investigate aborting prints.  Closed by a95ffe577531fbdfa70c8866a3cc2a48ac6f5f70.

**Comment by D1plo1d** [comment]
Yeah.. it helps to have a really bad quality FTDI cable which screws up enough to get lots of checksum issues. We just switched our FTDI and the problem went away but for people with shoddy FTDIs this is still a major problem. Is the default now to abort prints when you receive to many bad CRCs?

If you like I could actually trade FTDIs with you.. or you could try putting yours next to a rf transmitter/microwave :)

Actually.. stripping a ftdi cable of any shielding and subjecting it to lots of noise (RF) would probably be a really good torture test for makerbot serial communications
