### ISSUE TITLE
Accsees to Configuration file

### ISSUE THREAD

**Issue by Atntias** [makerbot/ReplicatorG#128]
Well for me i fried one of the analog pins and now i cant use the fimware from RepG (thermosistor is at pin7/6 not 3), so it could be nice to add some sort of acsses to the configurations file as a part of the software and not only by compilation, maby atleast for just few things like thermosistor input and motor selection.

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
