### ISSUE TITLE
ABP machine profile

### ISSUE THREAD

**Issue by charlespax** [makerbot/ReplicatorG#129]
Maybe RepG should have a machine profile for the Automated Build Platform. This would be nearly identical to the HBP profile. With the ABP profile selected the control panel would give no check box to run the fan. Instead, it would give an eject button that when pressed would run the ABP conveyor for thirty seconds or so.

It could also give wipe or purge options.

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
