### ISSUE TITLE
Remove motor speed option from control panel

### ISSUE THREAD

**Issue by charlespax** [makerbot/ReplicatorG#130]
PWMing the motor has been determined to damage the motor. The motor speed option should be removed from the ReplicatorG control panel. The motor options should be forward, stop, reverse.

Negatives:
-Some people will consider this a feature loss and get upset. (solution: they can use an older version of RepG.)

Positives:
-Nobody has to input 255 into the motor speed field to drive the motor.
-New people don't have to figure out on their own that they have to input 255 into the field. That is completely unintuitive.
-People will jack up their motors less often.
-The controls can be simplified

**Comment by DaveDurant** [comment]
I would much rather have a checkbox ("Allow dangerous PWM thing that may cause damage" or something) that enables people to still do this. Stepper are coming, people doing higher-rez prints need slower extruder speeds, support material relies on lower PWMs.

I don't think MBI saying "use an older version of the software" is a good solution.

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
