### ISSUE TITLE
Motor PWM warning

### ISSUE THREAD

**Issue by charlespax** [makerbot/ReplicatorG#131]
If PWMing motors damages them, RepG should warn the user if such commands are found in gcode.

**Comment by phooky** [comment]
That's a pretty big "if", tho.  Reopen when we have evidence.

**Comment by ssd2** [comment]
PWM can damage motors if the PWM frequency is a poor choice.  I believe there are several mechanisms that cause this, including resonance in the windings and capacitive coupling across bearings. Unfortunately, that's the limit of my understanding of it.

It is possible that the current choice is too high of a frequency.  Also, lowering the frequency may also offer a greater range of workable values, but may also make the motor louder.
