### ISSUE TITLE
Make it not require python install

### ISSUE THREAD

**Issue by ErikDeBruijn** [makerbot/ReplicatorG#134]
It should be possible to include a python runtime or something and not require a python installation? This would make it even more hassle free. Perhaps only download python if an installation is unavailable from the path.

**Comment by phooky** [comment]
This would be nice, but it's a huge amount of work to maintain this across all the platforms we support.

**Comment by ErikDeBruijn** [comment]
After a full day of work I've found a good way to do this. I will initiate a pull request when it's done. Only the windows build will need to be different and only minor Skeinforge source changes are required, which I'm already coordinating with Enrique. (The same for the progress bar feature's that I added. Enrique already accepted that one)

**Comment by ErikDeBruijn** [comment]
B.t.w. the changes I mentioned can be merged upstream without changing the workings of the normal way people will run it.
