### ISSUE TITLE
Read timed out

### ISSUE THREAD

**Issue by lanquarden** [makerbot/ReplicatorG#136]
While debugging my makerbot setup I noticed the following:

When I get following messages:
Read timed out.
Read timed out; trying to resend command.

monitoring the serial lines I do not see any command being resend... It gets stuck in a loop with the extruder running and forming a blob.

In line 238 of src/drivers/gen3/Sanguino3GDriver.java is the problem.

It only starts the inner while loop (listening for response) over again, without resending the package. If changed to 'continue start;' and just before the outer while loop (sending package) the label 'start:' is added it does what the message says it does. Other solution might be a similar statement like when CRC errors are detected.

**Comment by kintel** [comment]
Some work has been done here, are your problems fixed in 0021?

**Comment by kintel** [comment]
No feedback from original reporter. Assuming this has been fixed by now.

**Comment by lanquarden** [comment]
It was indeed fixed! Together with the new extruder firmware (2.6) I have not got a single read timed out issue! Thanks!
