### ISSUE TITLE
Motor failure mystery

### ISSUE THREAD

**Issue by charlespax** [makerbot/ReplicatorG#140]
While collecting data for the aparent motor issue people have been experiencing lately a discovery was made about the particular circumstances under which the motor will fail. The motor fails at approximately 16 seconds (~19 cycles) or not at all (using the gcode below). This was believed to be a random phenomenon, but is now determined to be dependent on the state of the machine. When running the test gcode on a freshly reset machine the motor will not fail. If, however, during a build Stop is pressed and the code run again, the motor will fail. Failure does not happen on the second run if the board is freshly reset, program run, allowed to complete, and run again.

M108 S255 (set extruder speed to maximum)
M101 (Extruder on, forward)
G04 P900 (Wait t/1000 seconds)
M103 (Extruder off)
G04 P5 (Wait t/1000 seconds)
M102 (Extruder on, reverse)
G04 P500 (Wait t/1000 seconds)
M101 (Extruder on, forward)
G04 P900 (Wait t/1000 seconds)
M103 (Extruder off)
G04 P5 (Wait t/1000 seconds)
M102 (Extruder on, reverse)
G04 P500 (Wait t/1000 seconds)
(repeat this cycle many times)

M101 (Extruder on, forward)
G04 P900 (Wait t/1000 seconds)
M103 (Extruder off)
G04 P5 (Wait t/1000 seconds)
M102 (Extruder on, reverse)
G04 P500 (Wait t/1000 seconds)

**Comment by charlespax** [comment]
Adam fixed this bug in git. It's some sort of synchronisation issue with RepG and the motherboard (I think). The fix should be out with RepG 21.

**Comment by phooky** [comment]
Fixed in 0021
