### ISSUE TITLE
Battery check and warning for live prints

### ISSUE THREAD

**Issue by ErikDeBruijn** [makerbot/ReplicatorG#143]
This feature would be great for fool-proof operation. At least at some point in each machine's life its operator will be distracted, especially when giving demonstrations, or generally when the operator is tired from working late hours hacking his machine the night before. It's really a shame to have a failed print that is unnecessary, moreover for non-5D prints it may cause extruders to not turn off (if you're unlucky) or cause a fire (if you're really unlucky).

The downside is that this needs to be implemented separately for each OS because different API's are involved. So this bugfix will require some testing, but I think it's worth it to solve this early rather than late (same for forced windows updates!).

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
