### ISSUE TITLE
Unable to successfully close RepG 21 in Ubuntu 10.04 after quitting the program

### ISSUE THREAD

**Issue by mifga** [makerbot/ReplicatorG#144]
To be honest, this might be because I'm using openjdk instead of traditional java, so this might not be a real issue, but I have twice been unable to quit the program and had to kill the process to stop it. --Matt

**Comment by kintel** [comment]
In ReplicatorG 0022 preferences, you can set control how much debug info printed. This should help trying to figure how where it hangs.
Of course, if you've got the courage, running ReplicatorG from Eclipse would provide the real answer ;)

**Comment by mifga** [comment]
Would me setting up an Eclipse environment be helpful? I would love to help figure out the issue that Nick and I were/are having with RepG21 on Ubuntu. And Charles pointed out I was being foolish about the openjdk -- that is not contributing to my issue. I'm running RepG20 just fine though.
