### ISSUE TITLE
machine cupkake cnc (sanguino 3g) building

### ISSUE THREAD

**Issue by 3dprintmotherfuckers** [makerbot/ReplicatorG#147]
comands are allways on 0,13% and they are not going forward. When we turn off and turn on the cupckake cnc makerbot start the print and the comands are slowly filling up.

**Comment by kintel** [comment]
I've noticed the same issue occasionally. My initial suspicion is that the Motherboard is spinning on a temperature-wait loop from a previous print/state, but this needs to be verified.

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
