### ISSUE TITLE
ReplicatorG can't write to directory Users/xxxx/.replicatorg

### ISSUE THREAD

**Issue by stmaus** [makerbot/ReplicatorG#170]
I tried moving the folder to my home directory and that didn't solve the problem.

**Comment by kintel** [comment]
Try removing the folder and try again.

The next version of ReplicatorG has a better error message giving you a little more information what, exactly, fails. Running from github will give you access to this.

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
