### ISSUE TITLE
ReplicatorG can't write to directory Users/xxxx/.replicatorg on OSX

### ISSUE THREAD

**Issue by stmaus** [makerbot/ReplicatorG#171]
I get an error that ReplicatorG can't write to the .replicatorg file in my home directory. No file existed so I created one and it still didn't solve the problem. I tried installing the folder in the Applications directory and my home directory.
What am I doing wrong?

**Comment by phooky** [comment]
~/.replicatorg is a directory, not a file.  If you've created a file there, then ReplicatorG won't be able to create a directory.  Remove the .replicatorg file and make sure ReplicatorG has the permissions to create a directory there.

(If this doesn't solve the issue, please reopen this issue and include the error text so I can track it down. Thanks!)
