### ISSUE TITLE
Test and integrate Skeinforge 36

### ISSUE THREAD

**Issue by kintel** [makerbot/ReplicatorG#172]
Download here: http://fabmetheus.crsndoo.com
Note: Cmd-line interface has changed: http://fabmetheus.blogspot.com/2010/11/demozendium.html

Makerbot patches will need some updating.
Evaluate whether any of the patches can be submitted to Skeinforge.

**Comment by petros** [comment]
Test http://fabmetheus.crsndoo.com Note: Cmd-line

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
