### ISSUE TITLE
Change jog feedrate in control panel to mm/s as used in skeinforge

### ISSUE THREAD

**Issue by mattproc** [makerbot/ReplicatorG#173]
Would be nice if this number actually meant something. I don't think it is actually mm/min as advertised right now either.

**Comment by kintel** [comment]
It's mm/minute as per G-code standard. This is also what is specified in machines.xml.
I agree that this could be clearer in the GUI.

**Comment by mattproc** [comment]
Whoops, I guess my issue is that the field only displays 3 digits. I only scrolled through it quickly and thought it went 0-1000, when it is actually 0-5000 (0-83mm/s I guess).

If I enter a four digit number and then resize the control panel, then the field displays correctly.
This is in skeinforge 21 on osx.

**Comment by kintel** [comment]
Also, the field size issue was fixed recently -> 0022.

**Comment by mattproc** [comment]
guess that solves this mystery!
