### ISSUE TITLE
Unable to run run-from-git.sh on Mac 10.5.8

### ISSUE THREAD

**Issue by mifga** [makerbot/ReplicatorG#174]
I have a clone of ReplicatorG on my system managed by git, but I cannot successfully run ./run-from-git.sh

Here is the terminal message:
digilosX-3:ReplicatorG mfgdigilx$ ./run-from-git.sh
Already up-to-date.
Buildfile: /Users/mfgdigilx/ReplicatorG/build.xml
     [echo] Mac OS X-i386

compile:
    [javac] /Users/mfgdigilx/ReplicatorG/build.xml:61: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 146 source files to /Users/mfgdigilx/ReplicatorG/build/classes
    [javac] /Users/mfgdigilx/ReplicatorG/src/org/j3d/loaders/collada/ColladaParser.java:108: cannot find symbol
    [javac] symbol  : method isEmpty()
    [javac] location: class java.lang.String
    [javac]             if (offset != null && !offset.isEmpty()) {  
    [javac]                                                      ^
    [javac] /Users/mfgdigilx/ReplicatorG/src/replicatorg/plugin/toolpath/SkeinforgeGenerator.java:222: method does not override a method from its superclass
    [javac]                 @Override
    [javac]                                  ^
    [javac] /Users/mfgdigilx/ReplicatorG/src/replicatorg/app/MachineFactory.java:78: cannot find symbol
    [javac] symbol  : method isEmpty()
    [javac] location: class java.lang.String
    [javac]                 if (!exp.isEmpty() && !exp.equals("0")) {
    [javac]                                         ^
    [javac] /Users/mfgdigilx/ReplicatorG/src/replicatorg/uploader/ui/BoardSelectionPanel.java:57: cannot find symbol
    [javac] symbol  : method isEmpty()
    [javac] location: class java.lang.String
    [javac]             if (iconStr != null && !iconStr.isEmpty()) {
    [javac]                                                        ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 4 errors

BUILD FAILED
/Users/mfgdigilx/ReplicatorG/build.xml:61: Compile failed; see the compiler error output for details.

Total time: 3 seconds

**Comment by kintel** [comment]
I believe Adam fixed this.
