### ISSUE TITLE
Homing Axis tests in the Control Panel

### ISSUE THREAD

**Issue by mifga** [makerbot/ReplicatorG#178]
I am testing a customer-release ToM in the BotCave now and am noticing some unexpected behaviors:
- in the "Homing" tab of the Control Panel there is an option for Home Z- but not Z+ (there is no Z-min endstop shipping default in the Thing-O-Matic). -- I've already told this to Adam, but this note should be here instead of in his memory.
- When you do Home an axis, the proper value does not propagate to the X-Position, Y-Position, Z-Position stepper control pane. This means that should you Home Y-min and then Center Y the stage will likely crash. (Actually, I"m noticing that if you center Y from any position it heads forward until it crashes after Homing Y-)

**Comment by mifga** [comment]
Additional detail: I strongly request that the Homing tab use the terms "MIN" and "MAX" instead of "-" and "+" as customers are not interpreting the "-" to mean "minus" and are having unexpected issues. If there is room, using the words that match the silkscreen on the boards themselves will really help clarify things! ;-)

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
