### ISSUE TITLE
RepG 22 Allows me to set an Extruder heat over 250

### ISSUE THREAD

**Issue by mifga** [makerbot/ReplicatorG#179]
Yes, this is a user error situation, but I don't gather we want users to have the option to create harmful fumes by going over 250ºC, do we? Perhaps a popup saying "please don't do this unless you really need to do this"? Something to force values at least 255 and under?

This ThingOMatic with Gen4 got to 280ºC without a hitch when I accidentally typoed. Will check to see if we fried the board now.

**Comment by charlespax** [comment]
Maybe we can put a max temp in the machine driver. This would keep MakerBots safe and allow other machines to do whatever they want.

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
