### ISSUE TITLE
skeinforge "support flow rate over operating flow rate" values should be < 1.0

### ISSUE THREAD

**Issue by DaveDurant** [makerbot/ReplicatorG#180]
Repg22 includes support structure goodness but the "support flow rate over operating flow rate" values mostly seem to be set at 2.0, which produces gcode that tells the extruder motor to run at (PWM) 510. This flow rate multiplier should really be under 1.0.

For MK4s, which can usually get down to at least around 200, with a profile that has speed\flow rate set to 255, a value of 0.78 (= 200/255) is probably safe.

Not having a MK5, I'm not sure how low the DC motor can go before it gets grumpy. It's the same easy math though: (min usable flow rate) / (flow rate).

**Comment by charlespax** [comment]
It is set to 2, so 510 appears in the gcode at the start of each run of support material. This is used for other scripts we're playing with. ReplicatorG treats everything 255 and greater as if it were 255. A setting of 2 does not affect function.

Many people are having problems PWMing the motors, so we're not going to make that a default.

**Comment by DaveDurant** [comment]
Not sure what those other scripts do but I think I'd argue that if some subset of the population (which I suspect is a minority) has problems PWMing the DC motors, support structures should be disabled by default. 

It seems like it would be better to have the feature setup correctly but disabled than have it setup incorrectly and enabled. People who don't have problems PWMing their extruder motor can just enable it, people who do have those problems can leave it off.
