### ISSUE TITLE
feature request: new M code for "wait for tool too cool down"

### ISSUE THREAD

**Issue by DaveDurant** [makerbot/ReplicatorG#181]
Similar to the M6 command that tells it to wait for things to be >= the set temperature, it'd be nice to have a command that tells it to wait for things to be <= the set temperature. 

This came out of a discussion in the MBI google group about automated printing. The idea would be to have this new command right after dropping the HBP temperature and right before poking the ABP to eject the just-printed part. 

(yes, this could be done with timed waits instead.. that's not as cool, though)

**Comment by kintel** [comment]
Actually, the M6 command waits for the temperature of both the heater and the build platform to heat _or_ cool until both are within predefined precision of the target temperatures (2 degrees celcius I believe). For this to work, you may need the development version of the Motherboard firmware though.

**Comment by DaveDurant** [comment]
Really? Wow - that was a fast implementation! :)

I guess this gets reworded to be "if the release FW doesn't do this already, it should."
