### ISSUE TITLE
Stopping the build leaves buttons disabled

### ISSUE THREAD

**Issue by JelleB** [makerbot/ReplicatorG#191]
Stopping a build leaves replicatorg in an unintended state. 
press build button (loaded separately generated gcode)
press stop;  
click ok on pop-up
simulate + build to file + reset + disconnect are enabled; build and other two next to it are disabled. 
Fix that sometimes works, often not: disconnect machine and reconnect again. If the arduino gets an new device entry (/dev/ttyUSB0 -> /dev/ttyUSB1), replicatorg seems to hang and needs a killall java before restarting.  

OS: ubuntu 10.04,
Java version "1.6.0_20" OpenJDK Runtime Environment
firmware: ultimaker, based on reprap5D, some local bug fixes wrt to cnc routing.

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Hi,

The new bug URL is:
http://replicatorg.lighthouseapp.com/projects/66325/tickets/54-stopping-the-build-leaves-buttons-disabled#ticket-54-1

Please follow up there if you get a chance.  Thanks!
