### ISSUE TITLE
release-23 improvements not merged into master

### ISSUE THREAD

**Issue by koenkooi** [makerbot/ReplicatorG#192]
The master branch is lacking a few improvements from the release-23 branch. See this diffstat:

Powerbook-3:ReplicatorG koen$ git diff origin/master origin/release-23 | diffstat
 b/build.xml                                      |    6 
 b/changelog.txt                                  |    9 
 b/examples/Attribution.txt                       |   25 
 b/examples/hexagon.stl                           |binary
 b/examples/trunicos40mm.stl                      |  814 
 b/examples/vase3.stl                             |  478 
 b/examples/wfu_cbi_skull.stl                     |438146 +++++++++++++++++++++++
 b/machines/makerbot.xml                          |   64 
 b/resources/images/button-panic.png              |binary
 b/src/replicatorg/app/Base.java                  |    2 
 b/src/replicatorg/app/ui/ControlPanelWindow.java |    1 
 b/src/replicatorg/app/ui/MainWindow.java         |   76 
 scripts/paraminator/paraminator.py               |  180 
 scripts/paraminator/test-objects/a.stl           | 2130 
 scripts/paraminator/test-objects/b.stl           | 1990 
 scripts/paraminator/test-objects/c.stl           | 2046 
 scripts/paraminator/test-objects/d.stl           | 1458 
 scripts/paraminator/test-objects/e.stl           | 2746 
 scripts/paraminator/test-objects/f.stl           | 2326 
 scripts/paraminator/test-objects/g.stl           | 2578 
 scripts/paraminator/test-objects/h.stl           | 2662 
 scripts/paraminator/test-objects/i.stl           | 1290 
 scripts/paraminator/test-objects/j.stl           | 2270 
 scripts/paraminator/test-objects/k.stl           | 2998 
 scripts/paraminator/test-objects/l.stl           | 1710 
 scripts/paraminator/test-objects/m.stl           | 2662 
 scripts/paraminator/test-objects/n.stl           | 2018 
 scripts/paraminator/test-objects/o.stl           | 1458 
 scripts/paraminator/test-objects/p.stl           | 1766 
 scripts/paraminator/test-objects/q.stl           | 2718 
 scripts/paraminator/test-objects/r.stl           | 2214 
 scripts/paraminator/test-objects/s.stl           | 2718 
 scripts/paraminator/test-objects/t.stl           | 1990 
 scripts/paraminator/test-objects/u.stl           | 1934 
 scripts/paraminator/test-objects/v.stl           | 2326 
 scripts/paraminator/test-objects/w.stl           | 2662 
 scripts/paraminator/test-objects/x.stl           | 3418 
 scripts/paraminator/test-objects/y.stl           | 2634 
 scripts/paraminator/test-objects/z.stl           | 2690 
 39 files changed, 439550 insertions(+), 59663 deletions(-)
Powerbook-3:ReplicatorG koen$

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
