### ISSUE TITLE
Feature request: accepting ngc files

### ISSUE THREAD

**Issue by peteruithoven** [makerbot/ReplicatorG#195]
I can't image this isn't requested already, but it would be great if ReplicatorG would also accept .ngc files. At the moment we have to rename all the files comming from Pycam.

**Comment by charlespax** [comment]
Please explain a bit more. What is a .ngc file? What are you renaming? What does the renaming accomplish?

**Comment by peteruithoven** [comment]
Pycam, a gcode generator, puts it's gcode into .ngc files. To open these in ReplicatorG we have to manually rename the files to .gcode files.

**Comment by charlespax** [comment]
Thanks for the report.

We use lighthouse for issue tracking. I've opened a report at http://replicatorg.lighthouseapp.com/projects/66325-replicatorg/tickets/59-feature-request-accepting-ngc-files#ticket-59-2.

If you have anything else to add, please add it there.
