### ISSUE TITLE
Add Bluetooth support for Linux

### ISSUE THREAD

**Issue by damonkohler** [makerbot/ReplicatorG#209]
This would require a small patch to RXTX as described here:

http://rxtx.qbang.org/wiki/index.php/Trouble_shooting#How_does_rxtx_detect_ports.3F__Can_I_override_it.3F

All that's needed is to add rfcomm\* to the list of scanned port prefixes.

**Comment by cibomahto** [comment]
Neat idea! We've moved issue reporting/feature requests to lighthouse though, I've opened a new ticket for this there:
http://replicatorg.lighthouseapp.com/projects/66325-replicatorg/tickets/128-feature-request-add-bluetooth-support-for-linux
