### ISSUE TITLE
only SF35-Thingomatic-ABP has new homing commands

### ISSUE THREAD

**Issue by kylemcdonald** [makerbot/ReplicatorG#224]
the new homing section in start.gcode is only in SF35-Thingomatic-ABP but not SF35-Thingomatic-HBP or others. i did a quick check by searching for M132.

**Comment by cibomahto** [comment]
Where are you looking? I see them all as having been updated (and they also appear correct in github):

sleipnir:prefs mattmets$ pwd
/Users/mattmets/Projects/repg-workspace/ReplicatorG/skein_engines/skeinforge-35/skeinforge_application/prefs
sleipnir:prefs mattmets$ fgrep -r M132 *
SF35-Thingomatic-ABP/alterations/start.gcode:M132 X Y Z A B (Recall stored home offsets for XYZAB axis)
SF35-Thingomatic-ABP-Stepstruder/alterations/start.gcode:M132 X Y Z A B (Recall stored home offsets for XYZAB axis)
SF35-Thingomatic-ABP-Stepstruder-1.75mm/alterations/start.gcode:M132 X Y Z A B (Recall stored home offsets for XYZAB axis)
SF35-Thingomatic-HBP/alterations/start.gcode:M132 X Y Z A B (Recall stored home offsets for XYZAB axis)
SF35-Thingomatic-HBP-Stepstruder/alterations/start.gcode:M132 X Y Z A B (Recall stored home offsets for XYZAB axis)
SF35-Thingomatic-HBP-Stepstruder-1.75mm/alterations/start.gcode:M132 X Y Z A B (Recall stored home offsets for XYZAB axis)
SF35-Thingomatic-non-heated/alterations/start.gcode:M132 X Y Z A B (Recall stored home offsets for XYZAB axis)

**Comment by kylemcdonald** [comment]
wow, looked closer and this is completely my mistake. i must have accidentally overwritten start.gcode with an older version at some point. my bad.
