### ISSUE TITLE
temperature is reset every time you open a file

### ISSUE THREAD

**Issue by kylemcdonald** [makerbot/ReplicatorG#225]
every time you open a new file, the platform and extruder temperatures are set back to 0.

i thought my calibration was wrong so i kept switching back and forth between printing and recalibrating, which caused the head to keep cooling down and warming up, which seemed to take a while.

eventually i figured out it was the other bug #224 causing the bad calibration.

**Comment by cibomahto** [comment]
Fixed here:
https://github.com/makerbot/ReplicatorG/commit/bc288b752b8602311195ca3c7bc0bb6d60e3e3c6

**Comment by kylemcdonald** [comment]
omg you're my hero. testing this tomorrow.
