### ISSUE TITLE
Jogging in Replicatorg-25

### ISSUE THREAD

**Issue by lemio** [makerbot/ReplicatorG#229]
When I try to move the 3D printer using the ´Manual Controls Panel´ (Jogging) the direction of the motors it just like random.  This is only with Replicatorg 25 and not with 24. I tested it on two different printers, one Mendel with RAMPS and one Darwin with weird electronics :) both using the fiveD firmware.

for more information see: http://wiki.makerbot.com/forum/t-364316

**Comment by phooky** [comment]
According to Matt Mets, fixed with
https://github.com/makerbot/ReplicatorG/commit/3c261bdd9c414bf398a37e88bedcdeac40c1e628
