### ISSUE TITLE
Easily accessible calibration tools

### ISSUE THREAD

**Issue by mifga** [makerbot/ReplicatorG#23]
Requested functionality: 
A instructions and/or tools with aid with calibrating the stepper motor movement direction and precision. 

A few possible solutions:
At simplest: diagram showing which direction the stage should go when x- axis is + or - (likewise y- and z-). 

At medium, integrate the tools to reverse the the polarity of the stepper motors to match operator's goals. (And also integrating the board reset that "fixes" the alignment reversal -- I'll submit that as a bug separately.)

At fantasy highest complexity, a barrage of simple benchmarking tools similar to inkjet or laser printer calibration tools to have the plastruder lay down rafts, weaves, circles, that will allow the operator to make adjustments so that at the end of adjustment the operator has confidence the bot is ready to print the design.

Op Notes:
When I open RepG to prepare to print on a bot with a plastruder head I haven't used before, I always throw open the Jog tool immediately to set the a temperature for some test extrusion, check the x-axis alignment, check the y-axis alignment, and reposition the build stage. While the Jog tool is a pretty good way to do this, my uses of the tool are all learned from experience and not particularly intuitively indicated by the UI.

**Comment by mifga** [comment]
Note, if you opt for simply an illustration to use as a guide for x-/y-/z-axis calibration, I'll be happy to make this for you if you give me a file format, resolution, and pixel dimensions (or request for vector based image).

**Comment by D1plo1d** [comment]
For reference EMC2 has a very nice calibration/setup wizard mostly targeting CNC mills and lathes. Taking a look at their wizard may be useful in designing a similar process for 3d printer calibration like you describe since I found it to be mostly a intuitive process (except when I had to leave the gui and hack the HAL, that stuff is evil).

+1 for a very handy idea. (especially on experimental extruders + cartesian bot designs)

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
