### ISSUE TITLE
Ability to configure interface, or offer public terminal version.

### ISSUE THREAD

**Issue by xamox** [makerbot/ReplicatorG#246]
I'm part of makerworks, it's a member based fabrication facility based in Ann Arbor and has only been open for a few months.

We currently have a makerbot, and of course it's very nice and as we ramp up we have been getting more people, and more that of course want to use the makerbot.

While the makerbot is nice and fancy and has lots of configuration options, this can also be a bit of a problem in a publicly shared type of situation.  What we would like to do is have the interface setup so that you basically can just load a file and print it.  Maybe like a replicator G lite or something.

The issue is that people are playing around with setting parameters, then the next person goes to use it and it's completely busted and we have go back and reconfigure the whole makerbot.

Do you think it's possible to add this type of functionality?

**Comment by FarMcKon** [comment]
xamos,
That sounds like an awesome project! We don't have that as goal, but we'd support someone else hacking or creating that kind of a feature.

If you want to learn some java, or hire a java developer, that could probably be added in 30-60 hours of code/debugging/testing.
