### ISSUE TITLE
Unable to set tool head temperature via control panel

### ISSUE THREAD

**Issue by dgwilson** [makerbot/ReplicatorG#247]
On 0029, latest r2... Mac version ... have configured 5D printing .... in the control panel you can enter the tool head temperature, then tab out of the field and it goes back to zero.

**Comment by kumy** [comment]
I can confirm this.

**Comment by FarMcKon** [comment]
Nice catch(es) folks, 
I <3 <3 <3 avoiding the mouse, so I'm all for fixing this.  

I thought someone had fixed this and checked it in, but I guess not.  I just updated ActionTextField to watch for 'VK_TAB' as a 'done editing' event.  That patch will be in our next release, or you can fetch and build from master branch and build yourself an update! just dist-mac.sh (or dist-all.sh) to build your own updated RepG.

**Comment by dgwilson** [comment]
Fix tested and confirmed to work. Thank you.
- David

David G. Wilson
http://dgwilson.wordpress.com
http://homepages.paradise.net.nz/dgwilson/

**Comment by FarMcKon** [comment]
glad to help!
