### ISSUE TITLE
Help>Offline Documentation could not load

### ISSUE THREAD

**Issue by BeauTurner** [makerbot/ReplicatorG#250]
Using ReplictorG-0029_r2 on Mac OSX v10.6.8 the Offline Documentation fails to load, message in window of ReplicatorG says: Could not load offline documentation. 

The Help>Supported GCodes does show as expected.

**Comment by FarMcKon** [comment]
I'll look into this.  You should have the files in 'docs/replicat.org/'. It is likely just a bad build.  We'll be sure to double check that before shipping out the final version of 0031.

Also, if you built it locally yourself, you won't have those docs unless you run 'ant cache-local-docs' before you build....
