### ISSUE TITLE
POM Use raft checkbox ignored

### ISSUE THREAD

**Issue by BeauTurner** [makerbot/ReplicatorG#251]
Using ReplictorG-0029_r2 on Mac OSX v10.6.8

The P-O-M Support section keeps checking the Use raft checkbox. If you uncheck, generate gcode and come back into the dialog it is now checked again (also ignores status of SF for raft on/off).

**Comment by BeauTurner** [comment]
Same issue reported as #248, closing this issue to avoid duplicate work (#248 still open and responded to by Far)

**Comment by FarMcKon** [comment]
Thanks for self-closing this.
