### ISSUE TITLE
Control panel fails to launch in 29_r2

### ISSUE THREAD

**Issue by chrisgilmerproj** [makerbot/ReplicatorG#252]
RepG 0029 r2 fails to launch control panel, an issue not seen in RepG 0028.  Responds with:

```
Packet response code: Unsupported command
Packet payload: empty
```

This was reported on a Makerbot Cupcake with Gen3 electronics:

```
Motherboard firmware v2.4 (Cupcake)
Toolhead 0: Extruder controller firmware v2.6 (Extruder)
```

**Comment by FarMcKon** [comment]
Chris, 
Can you send a bit more of the log my way (far@makerbot.com)?    Please turn log level up to 'Fine' in preferences, and send that log my way. I'd like to dig that quickly, and that would make it faster to reproduce.

Thanks for the bug report, we'll try to fix this soon.

**Comment by chrisgilmerproj** [comment]
Sure, I can do this.  Is there a place the log gets stored?  I'd love to send you the file.  Copying it off the actual application is proving to be difficult at log level FINE or higher.

**Comment by kyleder** [comment]
I'm having the same problem. If it helps my log entries on 'Fine' are:

[09:32:19] Creating panel for Pinch Wheel Extruder v1.1
[09:32:19] Packet response code: Unsupported command
[09:32:19] Packet payload: empty
[09:32:19] Error: payload not big enough.
[09:32:19] Current motor 1 PWM: 0

After that it returns to monitoring the temperature values.

Also, my machine info is as follows:

```
System Information
 ReplicatorG version: 0029_r2
 Java version: 1.6.0_29

Machine
 Profile Name: Cupcake Basic
 Driver Type: Sanguino3G
 Name: Matt's Cupcake
 Motherboard firmware version: Unknown v3.0
 Motherboard communication statistics
  Number of packets received from the USB interface:0
  Number of packets sent over the RS485 interface:9964
  Number of packets sent over the RS485 interface that were not responded to:0
  Number of packet retries attempted:0
  Number of bytes received over the RS485 interface that were discarded as noise:0

Machine Driver XML:
<machine>
        <name>Cupcake Basic</name>
        <geometry type="cartesian">
            <!-- different pulleys on X and Y axii -->
            <axis endstops="min" id="x" length="100" maxfeedrate="5000" stepspermm="11.767463"/> 
            <axis endstops="min" id="y" length="100" maxfeedrate="5000" stepspermm="11.767463"/>
            <axis endstops="min" id="z" length="100" maxfeedrate="150" stepspermm="320"/>
        </geometry>
        <tools>
            <tool fan="true" heater="true" material="abs" motor="true" name="Pinch Wheel Extruder v1.1" type="extruder"/>
        </tools>
        <clamps/>
        <driver name="sanguino3g">
            <!-- optional: <portname>COM1</portname> -->
            <rate>38400</rate>
        </driver>
        <warmup>
        </warmup>
        <cooldown>
(Turn off steppers after a build.)
M18
        </cooldown>
    </machine>
```

**Comment by kyleder** [comment]
Additionally, I downloaded ReplicatorG-0028 and the control panel worked under that version.

**Comment by rayherzog** [comment]
I have similar issue. Turns out that it really is the difference between MK5 and MK6 extruder choice.
When I select ToM with ABP and MK5 then the control panel does not open.
if I change to ToM/ ABP and MK6 it come up but since I have no stepper extruder it does obviously not work. The panel howver comes up.....will switch back to RepG-0028 for now and wait whether you can figure this one out.
thanks!

**Comment by chrisgilmerproj** [comment]
This is old so I'm closing.
