### ISSUE TITLE
avrdude fails on 64-bit Linux (Ubuntu 11.10 and earlier)

### ISSUE THREAD

**Issue by wcraigtrader** [makerbot/ReplicatorG#260]
# Problem

ReplicatorG includes a (mostly) statically-linked binary for avrdude, presumably for convenience.  The included binary is intended to run on both 32-bit and 64-bit versions of Linux, but it fails to do so on many 64-bit Linux systems because it is expecting to find the 32-bit version of libusb-0.1 installed.  On recent versions of Ubuntu, the 32-bit version of libusb-0.1 cannot be installed.

``` shell
$ git log avrdude
commit a17e24c7e8650497dba8f17e38704c71871a0bc3
Author: phooky <phooky@4a735864-2852-0410-872d-5d94fdcbaaf2>
Date:   Thu Sep 10 03:59:31 2009 +0000

    Creating universal package for i686 and x86_64 platforms
$ file avrdude
avrdude: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.2.0, not stripped
$ ldd avrdude
    linux-gate.so.1 =>  (0xf7795000)
    libusb-0.1.so.4 => not found
    libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf75ff000)
    /lib/ld-linux.so.2 (0xf7796000)
```
# Possible solutions:
1. Document the problem in the release notes!
2. Add a configuration option to choose which version of avrdude to use (RepG vs native).
3. Statically link avrdude against a 32-bit version of  libusb.
4. Stop distributing avrdude on Linux; depend upon the distributors to make avrdude available.

**Comment by FarMcKon** [comment]
Thanks for the note. We couldn't do #1 since we did not know this was a problem.   I just did fix #2 (just for fun)  Can you grab the latest version of master, and test it, let me know if it works? 

You can select 'use native uploader' in preferences. please try it out, and let me know how it goes.

**Comment by wcraigtrader** [comment]
I pulled the latest code from master, built it, ran it, checked 'use native uploader', then attempted to do a firmware push.

This appeared on the console:

``` bash
avrdude -C/opt/replicatorg-0031_Beta/tools/avrdude.conf -cstk500v2 -P/dev/ttyS0 -b115200 -D -Uflash:w:/home/ct7/.replicatorg/firmware/MB-mb24-2560-v3.1.hex:i -pm2560 
avrdude: error while loading shared libraries: libusb-0.1.so.4: wrong ELF class: ELFCLASS64
```

I then exited RepG and ran the same command from a shell prompt:

``` bash
$ which avrdude
/usr/bin/avrdude
$ avrdude -C/opt/replicatorg-0031_Beta/tools/avrdude.conf -cstk500v2 -P/dev/ttyS0 -b115200 -D -Uflash:w:/home/ct7/.replicatorg/firmware/MB-mb24-2560-v3.1.hex:i -pm2560 
avrdude: stk500_2_ReceiveMessage(): timeout
```

Then I restarted RepG, turned off the 'use native uploader' flag, then reran the test:

``` bash
/opt/replicatorg-0031_Beta/tools/avrdude -C/opt/replicatorg-0031_Beta/tools/avrdude.conf -cstk500v2 -P/dev/ttyS0 -b115200 -D -Uflash:w:/home/ct7/.replicatorg/firmware/MB-mb24-2560-v3.1.hex:i -pm2560 
/opt/replicatorg-0031_Beta/tools/avrdude: error while loading shared libraries: libusb-0.1.so.4: wrong ELF class: ELFCLASS64
```

My conclusion:  When the flag is set, RepG is running `avrdude` but the `PATH` is set to include the `replicatorg/avrdude` directory, and thus still running the RepG version of `avrdude` and not the native version.  Examination of the RepG startup script (`build/linux/dist/replicatorg`) will confirm this.  On line 12 it prepends the RepG tools directory to the PATH, and exports it, prior to starting RepG.

**Comment by wcraigtrader** [comment]
Further note:  I think that the lines in the startup script that prepend the RepG tools directory on the PATH before starting RepG are obsolete.  The only tool in the tools directory is avrdude, and that was already being called with an absolute path.  The comments prior to that reference jikes, which is probably legacy stuff leftover from forking the UI from the Arduino UI, which had it from Processing, which might actually have used the jikes Java compiler.  Thus removing those lines from the startup script would probably be a Good Thing, and would make this fix work correctly.
