### ISSUE TITLE
skip/combine movements that are too small

### ISSUE THREAD

**Issue by hoeken** [makerbot/ReplicatorG#43]
related to issue #42.  when drawing things comprised of many small line segments (such as an exploded ellipse from a DXF) the movement bogs down.  a filter that would not issue a movement until the total length exceeds a built-in threshold would hopefully prevent this from happening.  if done at the right level, it might even be able to solve #42 automatically.

**Comment by phooky** [comment]
http://replicatorg.lighthouseapp.com/projects/66325-replicatorg/tickets/4-skipcombine-movements-that-are-too-small
