### ISSUE TITLE
HTTP proxy support in startup script

### ISSUE THREAD

**Issue by Nazdravi** [makerbot/ReplicatorG#50]
Because replicatorg on every start tries to access the internet and i am behind a http proxy, i have added some lines to the "replicatorg" start script (Linux) to respect the system-wide proxy settings. Eventually this can be used generally. This works on the http_proxy environment variable.

if [ ${http_proxy} ]; then
  PROXY=`echo -n -e ${http_proxy} | sed -n 's/http:\/\/\([^:]\+\):\([1234567890]\+\)/-DproxySet=true -DproxyHost=\1 -DproxyPort=\2/p'`
  java $PROXY replicatorg.app.Base "$@"
else
  java replicatorg.app.Base "$@"
fi

**Comment by phooky** [comment]
Thanks for this; it's being rolled into the code for 0018.  There should be a beta by the end of the week.

**Comment by phooky** [comment]
In codebase, beta out
