### ISSUE TITLE
standalone gcode -> s3g and serial communications

### ISSUE THREAD

**Issue by koenkooi** [makerbot/ReplicatorG#74]
This is a feature request, not a bug :) It would be nice to have the gcode -> s3g and serial comms stuff as a seperate app as well. I'd like to control my makerbot using something like a beagleboard and the current repG would be overkill for that, I would only need the serial communications bit for that. To speed things up a bit, the gcode->s3g step can be done there as well.

**Comment by koenkooi** [comment]
preferably in something other than java, like c(++) or python :)

**Comment by ssd2** [comment]
It would be interesting to be able to have a command line tool to do gcode -> s3g so I could add it to the toolchain in my makefile.

**Comment by phooky** [comment]
This is definitely on my roadmap.

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
