### ISSUE TITLE
Support for cupcake + HBP with ACME rods

### ISSUE THREAD

**Issue by koenkooi** [makerbot/ReplicatorG#75]
I'm not sure what the right way is to post patches, but you can find the patch here:

http://github.com/koenkooi/ReplicatorG/commit/09b9d50f7869bcf5e2511c80f4421a1fc5f14e16

If needed I can add an non-HBP profile as well

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
