### ISSUE TITLE
Sync Profiles with Thingiverse Account

### ISSUE THREAD

**Issue by charlespax** [makerbot/ReplicatorG#77]
It would rock so hard to have my sf_profiles directory sync with my Thingiverse account.

**Comment by phooky** [comment]
Oh, DUDE.  Will probably have to wait until we start actively doing thingiverse work again, but yes, awesome idea.

**Comment by D1plo1d** [comment]
Best. Idea. Ever. +1

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
