### ISSUE TITLE
option for batch processing stl -> gcode + s3g

### ISSUE THREAD

**Issue by koenkooi** [makerbot/ReplicatorG#79]
I'm currentl building the cupcake transformer and the combined buildplates are too big for the hbp, so I'm building each part seperately. Going thru open-create-gcode-build-to-file is getting a bit tedious. It would be nice to have a batch option that would use the same profile for all .stls and create gcode + s3g in one go.

Bonus points for ABP integration :)

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
