### ISSUE TITLE
opening new file aborts current print

### ISSUE THREAD

**Issue by koenkooi** [makerbot/ReplicatorG#81]
During a long print it would be nice to be able to slice other files, but currently repG will abort the print. Related to this: build-to-file only works when a printer is connected and can't be used while printing.

**Comment by gpvillamil** [comment]
Yeah, I'm seeing this too, very annoying.

**Comment by phooky** [comment]
This will be fixed with the new backend; give it another couple of weeks.

**Comment by phooky** [comment]
The new backend is further off than I'd like, but we've got to get 0020 out the door, so it's for 0021.

**Comment by kintel** [comment]
build-to-file should now work with a disconnected printer (0022).

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
