### ISSUE TITLE
ReplicatorG STL preview axis labels

### ISSUE THREAD

**Issue by charlespax** [makerbot/ReplicatorG#82]
When looking at the awesome STL preview I cannot determine the final printed orientation of the object because there are not axis labels. This would be useful then using HBP or ABP because the bolt heads limit the build surface.

**Comment by koenkooi** [comment]
Or have an option to show the bolts in the 3d preview

**Comment by charlespax** [comment]
Showing the bolts would be cool. So the important stuff is the limits of the print area and the orientation. It's nice knowing which part of object will be facing out.
