### ISSUE TITLE
Improve thermistor lookup table distribution

### ISSUE THREAD

**Issue by greenlambda** [makerbot/ReplicatorG#86]
The current distribution of the ADC values in the thermistor lookup table are even across the entire range of it's operation, making for large errors (>20 C) in temperatures above 250 due to the non-linearity of the thermistor. This can be fixed by changing the distribution to be even along the temperatures instead. 

This isn't my idea, I'm just posting it here. More information, and the python script to do it are here: http://www.brokentoaster.com/blog/?p=148

It doesn't seem like too difficult a fix, so if you want I can see if I can create a patch.

EDIT: Clarified a little bit

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
