### ISSUE TITLE
aborting print leaves control panel temperature (and others?) twitchy

### ISSUE THREAD

**Issue by DaveDurant** [makerbot/ReplicatorG#87]
After aborting a print then heading to the control panel, I always find the temperature reads some random value - sometimes +20k, sometimes 17. 

It usually straightens itself out quickly but it's still a little flakey. Pressing jog buttons or forward/stop/reverse cause a drop to 0 in the temperature graph until repg is restarted.

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
