### ISSUE TITLE
stepper-enabled status in the control panel would be nice

### ISSUE THREAD

**Issue by DaveDurant** [makerbot/ReplicatorG#88]
It'd be nice if the control panel had indicators that let me know if I'd left the steppers enabled. Sometimes I mess with the jog buttons and forget to turn them off, which seems to cause them to heat up. A visual indication in the repg control panel would be nice.

**Comment by phooky** [comment]
This is a great idea.  It's going to require updates both to the firmware protocol and repG, but it should definitely get in there in the next month and change.  We're also planning on adding an "idle" mode in the next firmware version that will turn them off if the steppers have been inactive for a specified period of time.

**Comment by DaveDurant** [comment]
Double-bonus points for idle mode!!

**Comment by tmophoto** [comment]
thanks, that is fantastic news.

**Comment by phooky** [comment]
This didn't make it in for 0020 and the new firmware, pushing back to the next release set.

**Comment by ssd2** [comment]
Does this really require firmware changes?  Seems ReplicatorG could just guess based on the last command(s) it sent.   Of course, firmware support would be good too. :)

**Comment by phooky** [comment]
Good point; it could just display "unknown" in the status on connection.

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
