### ISSUE TITLE
model manipulation state hilighting

### ISSUE THREAD

**Issue by charlespax** [makerbot/ReplicatorG#90]
When using the model tab the user has no feedback as to which state they are in (View, Move, etc.). It would be nice if the current state were hilighted explicitly.

**Comment by phooky** [comment]
There's a big label at the top of the tool panel on the right that tells you what state you're in.  :)

But yeah, we should have something more obvious.  I'll give those buttons a toggled downstate.

**Comment by charlespax** [comment]
Ah, I should have looked harder. I suppose what I really want is upon opening a file the state to be Move

**Comment by charlespax** [comment]
Crap, I meant the default state should be VIEW.

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
