### ISSUE TITLE
feature request: integrated skeinforge should use a newer version..

### ISSUE THREAD

**Issue by DaveDurant** [makerbot/ReplicatorG#91]
I'll probably get thrown out for this one :) but I find the newer versions of skeinforge easier to configure than the 0006/0007 ones. ReplicatorG should use something that's a lot more recent and (IMO) easier to use.

**Comment by dataman** [comment]
I second that.  Current version is actually 27, makes 6 look very outdated.  Might I suggest some way of hooking in different versions of skeinforge?  Ala a Skienforge init command in configuration?
