### ISSUE TITLE
Loss of right side dialog buttons

### ISSUE THREAD

**Issue by dataman** [makerbot/ReplicatorG#92]
Main window right side dialog buttons are sometimes lost when switching from GCode view  back to Model view.  Appears that the Model view full window zooms.  There is no apparent way to reset the view other than to restart the program.  This appears to be bug similarly experienced in 017.   

I would suggest a Reset View under File or Edit which would reinitialize the viewport.

**Comment by phooky** [comment]
Hi,

Haven't been able to reproduce this; can you let me know what OS version you're using?

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
