### ISSUE TITLE
Dual monitor sillyness

### ISSUE THREAD

**Issue by charlespax** [makerbot/ReplicatorG#93]
I am running Ubuntu 10.04 with dual monitors and ReplicatoG from git.

Open a terminal on one  desktop. Execute "ant run" to open RepG. RepG should open on that desktop. Open an STL. It should open just fine. Move the ReplicatorG window to the second monitor. Attempt to open another STL. You will get the error "adding a container to a container on a different GraphicsDevice". Move the RepG  window  back to the first  desktop. Open an  STL. You will be able to open it.

**Comment by lotu** [comment]
What method are you using to do Dual Monitors?  (Xinermara, Dual Head, Twinview, etc.) What is you video card?  (ATI or Nvidia)  Which drivers are you using proprietary or free?  Are you using Gnome for your window manager or something else?  All this would help us replicate and isolate the issue.  Thank you.

**Comment by charlespax** [comment]
I have a stock Ubuntu 10.04 install. What commands would give the information you want?

a "lspci | grepnVidia" gives:
00:00.0 RAM memory: nVidia Corporation MCP78S [GeForce 8200] Memory Controller (rev a2)
00:01.0 ISA bridge: nVidia Corporation MCP78S [GeForce 8200] LPC Bridge (rev a2)
00:01.1 SMBus: nVidia Corporation MCP78S [GeForce 8200] SMBus (rev a1)
00:01.2 RAM memory: nVidia Corporation MCP78S [GeForce 8200] Memory Controller (rev a1)
00:01.3 Co-processor: nVidia Corporation MCP78S [GeForce 8200] Co-Processor (rev a2)
00:01.4 RAM memory: nVidia Corporation MCP78S [GeForce 8200] Memory Controller (rev a1)
00:02.0 USB Controller: nVidia Corporation MCP78S [GeForce 8200] OHCI USB 1.1 Controller (rev a1)
00:02.1 USB Controller: nVidia Corporation MCP78S [GeForce 8200] EHCI USB 2.0 Controller (rev a1)
00:04.0 USB Controller: nVidia Corporation MCP78S [GeForce 8200] OHCI USB 1.1 Controller (rev a1)
00:04.1 USB Controller: nVidia Corporation MCP78S [GeForce 8200] EHCI USB 2.0 Controller (rev a1)
00:07.0 Audio device: nVidia Corporation MCP72XE/MCP72P/MCP78U/MCP78S High Definition Audio (rev a1)
00:08.0 PCI bridge: nVidia Corporation MCP78S [GeForce 8200] PCI Bridge (rev a1)
00:09.0 SATA controller: nVidia Corporation MCP78S [GeForce 8200] AHCI Controller (rev a2)
00:0a.0 Ethernet controller: nVidia Corporation MCP77 Ethernet (rev a2)
00:10.0 PCI bridge: nVidia Corporation MCP78S [GeForce 8200] PCI Express Bridge (rev a1)
00:12.0 PCI bridge: nVidia Corporation MCP78S [GeForce 8200] PCI Express Bridge (rev a1)
00:13.0 PCI bridge: nVidia Corporation MCP78S [GeForce 8200] PCI Bridge (rev a1)
00:14.0 PCI bridge: nVidia Corporation MCP78S [GeForce 8200] PCI Bridge (rev a1)

**Comment by lotu** [comment]
Can you give us your /etc/X11/xorg.conf file.  Also, lsmod could be useful.  If it's a large file use pastebin.com to keep the topic neat.  I'm going to try to replicate it when I get home tonight.

**Comment by lotu** [comment]
I just did a test on an Ubuntu 10.4 laptop with a nvidia card on it.  I used nVidia proprietary drivers and Twinview.  However I could not reproduce the issue.  I do have a couple more questions that might help.  

Have you tested this with any other version of ReplicatorG?  If you find a version that works please do a bisection to find the change that caused the problem.  The stl file opens a 3D, what happens to that 3D view when you move to the other screen?  Can you still rotate the object in it?  Also do other 3D applications have issues moving between monitors?  If you start on the 2nd monitor what happens?  There are probably at least half a dozen different ways of configuring dual screens, and they all break in different ways so any extra info about how you set up your dual screens would be helpful.

Sorry for all the questions but hopefully this can help us isolate the issue.

**Comment by charlespax** [comment]
My system does not have an xorg.conf file. For lsmod see http://pastebin.com/4dsvxGBZ

I'll need some time to get the other information.

**Comment by lotu** [comment]
Okay, looks like from your modules you have an ATI graphics card.  ATI unfortunately is know to cause problems.  Do a lspci with out greping anything to confirm that.

**Comment by charlespax** [comment]
lspci gives http://pastebin.com/Mpm9iTve

**Comment by lotu** [comment]
Well you have an ATI graphics card, this makes it impossible for me to test this for you, because I do not have an ATI graphics card.  I know ATI cards have a long history of problems with Linux.  I'm inclined to suspect that this problem is not will occur with other applications that use 3d and maybe more of a bug in the drivers. You should make a backup and try a different method of doing dual screens.  See http://ubuntuforums.org/showthread.php?t=221174 and http://en.gentoo-wiki.com/wiki/X.Org/Dual_Monitors/ATI if this works then you can assume that the problem was with the original method of doing dual screens.

**Comment by charlespax** [comment]
I'll talk to Adam about this and see if it's worth investigating further.

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
