### ISSUE TITLE
stl preview build volume should be obtained from machines.xml

### ISSUE THREAD

**Issue by Lenbok** [makerbot/ReplicatorG#94]
The stl preview pane seems to be fixed at 10cm x 10cm x 10cm. This may not correspond to the build volume of the machine the user has selected, e.g. reprap mendel using makerbot firmware, or self-built or prototype makerbots with non-standard dimensions.  It would make sense to obtain these dimensions from entries in the machines.xml (I am guessing that a new axis attribute would be needed, as the definition of the existing length attribute sounds like it may not correspond to the actual buildable length on that axis).

**Comment by ErikDeBruijn** [comment]
I've fixed this!!

commit a49de32b98b410aa885d1fb3af38e9ac2ac202bb
http://github.com/ErikDeBruijn/ReplicatorG-Erik5D/tree/feature-configurablebuildvolumes
Author: Erik de Bruijn reprap@erikdebruijn.nl
Date:   Thu Oct 21 23:52:37 2010 +0200

```
STL preview now is the actual build volumes configured in machines.xml.
In response to issue #94 by Lenbok. Before it was fixed to 100x100x100mm.
Now it reads the values from the machines.xml files and updates when a
different machine is selected. The BuildVolumes object currently contains
a very simple model of the machine's volume (a 3D block), but there's room
for adding cutouts and keep-out zones (e.g. nozzle cleaning brushes)
that can also be displayed.

http://github.com/makerbot/ReplicatorG/issues#issue/94
```
