### ISSUE TITLE
feature request: include start.txt/end.txt gcode via ReplicatorG

### ISSUE THREAD

**Issue by DaveDurant** [makerbot/ReplicatorG#98]
It might be nice if I could tell RepG about my start.txt and end.txt files instead of feeding them to Skeinforge. 

This would make things like sharing gcode and conveyer belts (with a mid.txt?) a bit easier. Maybe.

**Comment by lotu** [comment]
Interesting idea, part of this might be accomplished by the scripts panel.  So you could attach the start and end codes to a button in the control panel.  It wouldn't be automatic but it still might be helpful.

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
